"""empty message

Revision ID: a86a3f33c009
Revises: 
Create Date: 2022-08-08 19:45:11.139694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86a3f33c009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_key', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('invoice',
    sa.Column('invoice_no', sa.String(length=10), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('route_plan', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=225), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_amount', sa.String(length=20), nullable=True),
    sa.Column('paid_amount', sa.String(length=20), nullable=True),
    sa.Column('balance_amount', sa.String(length=20), nullable=True),
    sa.Column('pending_since', sa.String(length=20), nullable=True),
    sa.Column('cash', sa.String(length=20), nullable=True),
    sa.Column('cheque_amount', sa.String(length=25), nullable=True),
    sa.Column('bank_name', sa.String(length=256), nullable=True),
    sa.Column('cheque_number', sa.String(length=35), nullable=True),
    sa.Column('cheque_date', sa.String(length=15), nullable=True),
    sa.Column('neft_amount', sa.String(length=30), nullable=True),
    sa.Column('utrn_number', sa.String(length=35), nullable=True),
    sa.Column('neft_date', sa.String(length=15), nullable=True),
    sa.Column('common_cheque', sa.String(length=10), nullable=True),
    sa.Column('no_collection', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.UnicodeText(), nullable=True),
    sa.Column('note_2000', sa.String(length=8), nullable=True),
    sa.Column('note_500', sa.String(length=8), nullable=True),
    sa.Column('note_200', sa.String(length=8), nullable=True),
    sa.Column('note_100', sa.String(length=8), nullable=True),
    sa.Column('note_50', sa.String(length=8), nullable=True),
    sa.Column('note_20', sa.String(length=8), nullable=True),
    sa.Column('note_10', sa.String(length=8), nullable=True),
    sa.Column('coins', sa.String(length=8), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('transaction', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('invoice_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('admin')
    # ### end Alembic commands ###
